#!/usr/bin/env python3

import json
import locale
import sys
from reports import generate as generate_report
from emails import generate as generate_email
from emails import send as send_email

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = 0
  top_car = {}
  year = {}
  year_sales = {}

  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item

    # TODO: also handle max sales
    item_sales = item["total_sales"]
    if item_sales > max_sales:
      max_sales = item_sales
      top_car = item

    # TODO: also handle most popular car_year
    car = item["car"]
    y = car["car_year"]
    if y not in year:
      year[y] = 1
      year_sales[y] = item["total_sales"]
    else:
      year[y] += 1
      year_sales[y] += item["total_sales"]

  max_year = max(year, key = year.get)
  best_year_sales = year_sales[max_year]
 
  summary = [
    "The {x} generated the most revenue: ${y}".format(x = format_car(max_revenue["car"]), y = max_revenue["revenue"]),
    "The {x} had the most sales: {y}".format(x = format_car(top_car["car"]), y = max_sales),
    "The most popular year was {x} with {y} sales.".format(x = max_year, y = best_year_sales)
  ]
  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)

  # TODO: turn this into a PDF report
  final_report = ""
  for i in summary:
    final_report = final_report + i + "<br/>"
  generate_report("/tmp/cars.pdf", "Car Sales Report", final_report , cars_dict_to_table(data))

  # TODO: send the PDF report as an email attachment
  email_report = ""
  for i in summary:
    email_report = email_report + i  + "\n"
  e = generate_email("automation@example.com", "student-02-b2388b6dec25@example.com", "Sales summary for last month", email_report, "/tmp/cars.pdf")
  send_email(e)

  